<<<<<<< HEAD
# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

sass:
  sass_dir: assets/css
  style: :nested

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Alex Sheen"
description:	       "Millennial Jekyll Theme"
author:              "Paul Le"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
=======
title: Alex Sheen
logo: /assets/img/logo.png
description: Portfolio
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
>>>>>>> 6263b79927602035546f45bed888f5b8ed7edd33
