title: Alex Sheen
logo: /assets/img/logo.png
description: Portfolio
show_downloads: true
google_analytics:
<<<<<<< HEAD
theme: jekyll-theme-minimal
=======

# The following settings are NECESSARY for the Prologue theme to run:
theme: jekyll-theme-minimal
collections: [sections]
>>>>>>> 960b2ae8aee835156dca3490e07e77be13161c9a
